name: Build and Push to GHCR

on:
    push:
        branches: [ main ]
        paths: [ '**.js', '**.jsx', '**.ts' ]
    pull_request:
        branches: [ main ]
        paths: [ '**.js', '**.jsx', '**.ts' ]
    workflow_dispatch:

jobs:
    linter:
        name: linter check
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0
            -   name: Super-Linter
                uses: super-linter/super-linter@v8.5.0
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    # Scan only changed files
                    VALIDATE_ALL_CODEBASE: false
    bun:
        name: bun-job
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: oven-sh/setup-bun@v2

            -   run: bun install --frozen-lockfile
            #            -   run: bun run dev
            -   run: bun run build
    build-and-push:
#        needs: [ linter, bun ]
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: Log in to GHCR
                uses: docker/login-action@v3
                with:
                    registry: ${{ env.REGISTRY }}
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
            -   name: Extract metadata (tags, labels)
                id: meta
                uses: docker/metadata-action@v5
                with:
                    images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                    tags: |
                        type=raw,value=latest,enable={{is_default_branch}} 
                        type=sha,format=short
            -   name: Build and push Docker image
                uses: docker/build-push-action@v6
                with:
                    context: .
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}